apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: echo-good-morning
spec:
  steps:
    - name: echo
      image: alpine
      script: |
        echo "Good Morning!"
      resources:
        requests:
          memory: 100Mi
        limits:
          memory: 1Gi
