kind: Task
apiVersion: tekton.dev/v1
metadata:
  name: write-array-results
spec:
  results:
    - name: array-results
      type: array
  steps:
    - name: write-array
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo -n "[\"hello\",\"world\"]" | tee $(results.array-results.path)