kind: Task
apiVersion: tekton.dev/v1
metadata:
  name: write-object-results
spec:
  results:
    - name: object-results
      type: object
  steps:
    - name: write-object
      image: bash:latest
      script: |
        #!/usr/bin/env bash
        echo -n "{\"hello\":\"world\"}" | tee $(results.object-results.path)