apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-finally2
spec:
  tasks:
  - name: test1
    taskRef:
      name: noop
    params:
      - name: RETURN_CODE
        value: "1"
    retries: 2
  - name: test2
    taskRef:
      name: noop
    params:
      - name: RETURN_CODE
        value: "1"
    retries: 2
  finally:
    - name: cleanup
      taskRef:
        name: noop
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-finally2-run
spec:
  pipelineRef:
    name: test-finally2
  timeout: 2m
