apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: cluster-resolver-tr
spec:
  taskRef:
    resolver: cluster
    params:
    - name: kind
      value: task
    - name: name
      value: v1-task
    - name: namespace
      value: foo