apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: good-morning-run-
spec:
  workspaces:
  - name: source
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
  - name: other
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Mi
  pipelineSpec:
    workspaces:
    - name: source
    tasks:
    - name: parallel-1
      taskSpec:
        workspaces:
        - name: source
        steps:
        - image: busybox
          script: |
            echo $(workspaces.source.path)
            sleep 60
      workspaces:
      - name: source
    - name: parallel-2
      taskSpec:
        workspaces:
        - name: other
        steps:
        - image: busybox
          script: |
            echo $(workspaces.other.path)
            sleep 60
      workspaces:
      - name: other
    - name: last
      taskSpec:
        workspaces:
        - name: source
        - name: other
        steps:
        - image: busybox
          script: |
            echo $(workspaces.source.path)
            echo $(workspaces.other.path)
            sleep 60
      runAfter: ["parallel-1", "parallel-2"]
      workspaces:
      - name: source
      - name: other