apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: image-build-task
spec:
  steps:
    - name: build
      image: busybox
      resources:
        requests:
          cpu: 1
        limits:
          cpu: 2
    - name: echo
      image: busybox
      resources:
        requests:
          cpu: 1
        limits:
          cpu: 4
