apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: good-morning-run-{{.Iteration}}
spec:
  pipelineSpec:
    tasks:
    - name: echo-good-morning
      taskSpec:
        steps:
          - name: echo
            image: ubuntu
            script: |
              #!/usr/bin/env bash
              echo "Good Morning!"
              sleep 10