apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
 name: say-hi-retries
spec:
 timeouts:
   pipeline: 1m
   tasks: 30s
 pipelineSpec:
   tasks:
     - name: hi
       retries: 5
       taskSpec:
         steps:
           - name: hi
             image: alpine:3.12
             script: |
               echo 'hi'
               sleep 7
               exit 1
