apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: v1-pipeline
spec:
  tasks:
  - name: first
    taskRef:
      name: my-cluster-task
      kind: ClusterTask
---
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: v1-pipelinerun
spec:
  pipelineRef:
    name: v1-pipeline