apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: empty-properties
spec:
  results:
    - name: object-results
      type: object
      properties: {}
  steps:
  - image: bash
    script: |
      echo -n "{\"IMAGE_URL\":\"ar.com\", \"IMAGE_DIGEST\":\"sha234\"}" > $(results.object-results.path)