apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nil-properties
spec:
  results:
    - name: object-results
  steps:
  - image: bash
    script: |
      echo -n "{\"IMAGE_URL\":\"ar.com\", \"IMAGE_DIGEST\":\"sha234\"}" > $(results.object-results.path)