apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  restartPolicy: Never
  containers:
  - command: ["sh", "-c", "exit 1"]
    image: busybox
    name: fail
  - command: ["sh", "-c", 'echo "Hello, Kubernetes!" && sleep 36000']
    image: busybox
    name: sleep
