apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: my-task
spec:
  params:
  - name: test-type
  steps:
  - image: busybox
    script: "echo hello"
---
apiVersion: custom.tekton.dev/v1alpha1
kind: TaskLoop
metadata:
  name: testloop
spec:
  taskRef:
    name: my-task
  iterateParam: test-type
  retries: 2
